/**
 * In-browser perf harness (ROADMAP.md Phase 0.2).
 *
 * Loaded ONLY when the URL contains ?perf=1 (see main.js). Exposes
 * window.__rmtPerf:
 *
 *   __rmtPerf.loadStress('chain-1000')  // swap current composition for a
 *                                       // stress module (reloads the page;
 *                                       // your previous work stays in undo
 *                                       // history is replaced — use
 *                                       // restoreDefault() to go back)
 *   __rmtPerf.restoreDefault()          // clear snapshot -> default module
 *   __rmtPerf.measureEval(10)           // full module re-evaluation
 *   __rmtPerf.measureCommit(10)         // END-TO-END commit: octave up/down
 *                                       // via eventBus (expression rewrite +
 *                                       // dirty marking + evaluate + renderer
 *                                       // sync + history snapshot)
 *   __rmtPerf.report()                  // run both + console.table summary
 *
 * Stress modules are generated by scripts/perf/generate-stress-module.mjs
 * into public/modules/perf/.
 */

import { getModule } from '../store/app-state.js';
import { eventBus } from '../utils/event-bus.js';

const SNAPSHOT_KEY = 'rmt:moduleSnapshot:v1';

function percentile(sorted, p) {
  const idx = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length));
  return sorted[idx];
}

function stats(samples) {
  const s = [...samples].sort((a, b) => a - b);
  return {
    'p50 (ms)': +percentile(s, 50).toFixed(2),
    'p95 (ms)': +percentile(s, 95).toFixed(2),
    'min (ms)': +s[0].toFixed(2),
    'max (ms)': +s[s.length - 1].toFixed(2),
    runs: s.length
  };
}

function requireModule() {
  const mod = getModule();
  if (!mod) throw new Error('[perf] module not ready yet');
  return mod;
}

function noteCount(mod) {
  return Object.keys(mod.notes).length;
}

function evaluatorName(mod) {
  return mod?._binaryEvaluator?.constructor?.name || 'unknown';
}

function pickMidNoteId(mod) {
  const ids = Object.keys(mod.notes).map(Number).filter((id) => id !== 0).sort((a, b) => a - b);
  return ids[Math.floor(ids.length / 2)];
}

async function loadStress(name) {
  const res = await fetch(`modules/perf/${name}.json`);
  if (!res.ok) throw new Error(`[perf] fetch failed for ${name}: ${res.status}`);
  const data = await res.json();
  localStorage.setItem(SNAPSHOT_KEY, JSON.stringify(data));
  console.log(`[perf] snapshot set to ${name} (${data.notes.length} notes); reloading…`);
  location.reload();
}

function restoreDefault() {
  localStorage.removeItem(SNAPSHOT_KEY);
  console.log('[perf] snapshot cleared; reloading to default module…');
  location.reload();
}

function measureEval(iterations = 10) {
  const mod = requireModule();
  const samples = [];
  for (let i = 0; i < iterations; i++) {
    mod._incrementalEvaluator.invalidateAll();
    mod._dirtyNotes.add(0);
    const t0 = performance.now();
    mod.evaluateModule();
    samples.push(performance.now() - t0);
  }
  const result = stats(samples);
  console.table({ [`full eval (${noteCount(mod)} notes, ${evaluatorName(mod)})`]: result });
  return result;
}

function measureCommit(iterations = 10, noteId = null) {
  const mod = requireModule();
  const id = noteId ?? pickMidNoteId(mod);
  const samples = [];
  // Pair up/down so the module ends unchanged (history gains entries).
  for (let i = 0; i < iterations; i++) {
    for (const direction of ['up', 'down']) {
      const t0 = performance.now();
      eventBus.emit('player:octaveChange', { noteId: id, direction });
      samples.push(performance.now() - t0);
    }
  }
  const result = stats(samples);
  console.table({ [`end-to-end commit (note ${id}, ${evaluatorName(mod)})`]: result });
  return result;
}

function report() {
  const mod = requireModule();
  const summary = {
    notes: noteCount(mod),
    evaluator: evaluatorName(mod),
    'full eval': measureEval(),
    'commit e2e': measureCommit()
  };
  console.log('[perf] summary', summary);
  return summary;
}

function info() {
  const mod = requireModule();
  return { notes: noteCount(mod), evaluator: evaluatorName(mod) };
}

// Debug escape hatch for driving/diagnosing from automation.
function getModuleRef() {
  return getModule();
}

window.__rmtPerf = { loadStress, restoreDefault, measureEval, measureCommit, report, info, getModuleRef };
console.log('[perf] harness ready: window.__rmtPerf — loadStress(name) | restoreDefault() | measureEval() | measureCommit() | report()');
